android.useAndroidX=true
android.enableJetifier=true
org.gradle.java.home=C\:\\Program Files\\Android\\Android Studio\\jbr
android.javaCompile.suppressSourceTargetDeprecationWarning=true

# Increase Gradle JVM memory
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -XX:+UseParallelGC

# Enable parallel builds
org.gradle.parallel=true
org.gradle.caching=true
