/**
 * AUTO-GENERATED by scripts/sync-capability-docs.ts
 * DO NOT EDIT MANUALLY — edit the source in lib/capabilities/<id>.ts instead.
 */

import { FirebaseCapabilityDoc } from './types';

const aiCapability: FirebaseCapabilityDoc = {
    id: "ai",
    displayName: "AI",
    minVersion: "1.0.0",
    docs: `🤖 AI (AppacadabraAI)
- **Fluent Builder API**: Chain methods to configure AI generation.
- **Builder Methods** (chainable — call \`generate()\` last):
    - \`generate(prompt, callback)\`: Execute the AI request with the configured options.
    - \`withSearch()\`: Enable Google Search grounding for real-time info.
    - \`withSchema(jsonSchemaObj)\`: Force structured JSON output matching the schema.
    - \`fromImage(input)\`: Attach image(s) for vision analysis or image generation. Accepts a single Base64 string OR an array (up to 14). Typically the base64 comes from \`AppacadabraCamera.takePhoto()\`.
    - \`fromVideo(input)\`: Attach video(s) for analysis/summarization. Accepts a single Base64 string OR an array. Typically the base64 comes from \`AppacadabraCamera.recordVideo()\`.
    - \`fromAudio(input)\`: Attach audio(s) for transcription/analysis. Accepts a single Base64 string (from \`AppacadabraAudio.recordStop\`) OR an array.
    - \`generateVideo(prompt, callback)\`: Generate a video from text (standalone) OR animate up to 3 reference images (chained). Returns base64 MP4. When chained with \`fromImage\`, the first image becomes the starting frame and up to 2 additional images serve as style references. The callback receives \`(success, videoBase64, thumbnailBase64)\` — \`thumbnailBase64\` is always a JPEG base64: the first frame of the video when extraction succeeds, or a static dark placeholder with a play icon when it fails. Ready to use as an \`<img>\` preview while the video loads.
    - \`generateImage(prompt, callback)\`: Generate an image from text (standalone) OR edit/remix up to 14 input images (chained with \`fromImage\`). Returns base64 PNG.
    - **Standalone-only Methods** (NOT chainable — call directly on \`AppacadabraAI\`):
    - \`similarity(itemsArray, callback)\`: Compute semantic similarity between 2+ text strings. Returns a JSON object with a pairwise similarity \`matrix\` (values 0.0-1.0) and \`count\`.
    - \`parseJSON(resultString)\` - **Utility**: safely extract a JSON object/array from an AI response string (strips markdown code fences automatically). Returns the parsed value or \`null\` on failure. **Use instead of writing a custom \`extractJSON\` helper.**
        - **Example**: \`const data = AppacadabraAI.parseJSON(resultString); if (!data) { AppacadabraUI.toast("Parse error", "error"); return; }\`
- **Examples**:
    - Basic: \`AppacadabraAI.generate("Hello", callback)\`
    - Search: \`AppacadabraAI.withSearch().generate("Who won the game?", callback)\`
    - JSON: \`AppacadabraAI.withSchema({ type: "object", properties: { ... } }).generate("Extract data", callback)\`
    - Single image: \`AppacadabraAI.fromImage(base64).generate("Describe this", callback)\`
    - Multiple images: \`AppacadabraAI.fromImage([img1, img2, img3]).generate("Compare these images", callback)\`
    - Single video: \`AppacadabraAI.fromVideo(videoBase64).generate("Summarize this video", callback)\`
    - Single audio: \`AppacadabraAI.fromAudio(base64).generate("Transcribe this", callback)\`
    - Multiple audios: \`AppacadabraAI.fromAudio([audio1, audio2]).generate("Compare these recordings", callback)\`
    - *Chained*: \`AppacadabraAI.withSearch().withSchema(schema).generate("Find data...", callback)\`
    - Image Gen: \`AppacadabraAI.generateImage("A cute cat wearing a hat", "onImageReady")\`
    - Image edit (from takePhoto): \`AppacadabraAI.fromImage(photoBase64).generateImage("Make the sky purple", "onImageReady")\`
    - Image remix (multiple): \`AppacadabraAI.fromImage([img1, img2]).generateImage("Blend these styles", "onImageReady")\`
    - Video Gen: \`AppacadabraAI.generateVideo("A cinematic drone shot of a beach", "onVideoReady")\`
    - Image-to-video: \`AppacadabraAI.fromImage(photoBase64).generateVideo("Bring this photo to life with gentle movement", "onVideoReady")\`
    - Multi-image-to-video: \`AppacadabraAI.fromImage([img1, img2]).generateVideo("Animate blending these scenes", "onVideoReady")\`
    - Similarity (2 items): \`AppacadabraAI.similarity(["cat", "kitten"], "onResult")\` → \`{ matrix: [[1, 0.87], [0.87, 1]], vectors: [[0.1, ...], [0.12, ...]], count: 2 }\`
    - Similarity (3+ items): \`AppacadabraAI.similarity(["dog", "puppy", "car"], "onResult")\` → \`{ matrix: [[1, 0.91, 0.12], [0.91, 1, 0.10], [0.12, 0.10, 1]], vectors: [...], count: 3 }\`
- **Return (generate)**: Generated text (string). If \`withSchema\` is used, result is a JSON string.
- **Return (generateImage)**: Complete DataURI string (e.g. \`data:image/png;base64,...\`). Use directly as img src (do NOT append prefixes manually).
- **Return (generateVideo)**: Callback receives \`(success, videoDataUri, thumbnailDataUri)\`. Use directly as src. Example: \`function onVideoReady(ok, videoUri, thumbUri) { if (thumbUri) img.src = thumbUri; vid.src = videoUri; }\`
- **Return (similarity)**: JSON string \`{ matrix: number[][], vectors: number[][], count: number }\`. \`matrix\` = pairwise cosine similarity (symmetric, 1.0 on diagonal, 0.0-1.0). \`vectors\` = raw embedding arrays (optional, for advanced use like caching or custom distance).`,
};

export default aiCapability;
