/**
 * AUTO-GENERATED by scripts/sync-capabilities.ts
 * DO NOT EDIT MANUALLY — edit the source in lib/capabilities/<id>.ts instead.
 */

import { FirebaseCapabilityDoc } from './types';

const audioCapability: FirebaseCapabilityDoc = {
    id: "audio",
    displayName: "Audio",
    minVersion: "1.0.0",
    docs: `🎙️ AUDIO (AppacadabraAudio)
- \`recordStart(callback)\` - Start audio recording (M4A/AAC)
    - **Return**: "Recording started"
- \`recordStop(callback)\` - Stop recording and get result
    - **Callback Data (string)**: Complete DataURI string (\`data:audio/m4a;base64,...\`). **CRITICAL**: Use this string immediately with \`AppacadabraAI.fromAudio(uri).generate(...)\` or in an \`<audio>\` tag. do NOT append prefixes.
    - **Example**: \`AppacadabraAudio.recordStop("onAudioRecorded")\`
- \`speak(text, options, callback)\` - Speak text aloud using device TTS engine (free)
    - **options** (object, optional): \`{ language?: "en-US"|"pt-BR"|..., pitch?: 0.5-2.0, rate?: 0.5-2.0, volume?: 0.0-1.0 }\`
    - **Return**: "Speaking" (string)
    - **Example**: \`AppacadabraAudio.speak("Hello world", { language: "en-US", rate: 1.0 }, "onSpeakDone")\`
- \`speakAI(text, options, callback)\` - Generate high-quality AI voice using Gemini TTS (costs Mana ⚡)
    - **options** (object, optional): \`{ voice?: "Aoede"|"Charon"|"Fenrir"|"Kore"|"Puck"|"Orbit"|"Zephyr", language?: "en-US"|"pt-BR"|... }\`
    - Default voice: "Aoede". Cost: ~0.01–0.05 Mana per sentence (depends on text length)
    - Use \`speak()\` for free device TTS; use \`speakAI()\` when voice quality matters
    - **Return**: "Speaking" (string) — callback called when audio starts playing
    - **Example**: \`AppacadabraAudio.speakAI("Welcome to your spell!", { voice: "Kore" }, "onSpeakDone")\`
- \`stopSpeaking(callback)\` - Stop ALL speech (current + queued)
    - **Return**: "Stopped" (string)
- \`isSpeaking(callback)\` - Check if currently speaking
    - **Return**: "true" or "false" (string)

--- VOICE INPUT WORKFLOW (EXAMPLE) ---
\`\`\`javascript
function onMicrophoneClick() {
  if (!isRecording) {
    AppacadabraAudio.recordStart("onStart");
  } else {
    AppacadabraAudio.recordStop("onAudioResult");
  }
}

window.onAudioResult = function(success, base64) {
  if (success) {
    AppacadabraAI.fromAudio(base64)
      .withSchema(mySchema)
      .generate("Extract data from this audio", "onAIProcessed");
  }
}
\`\`\``,
};

export default audioCapability;
