/**
 * AUTO-GENERATED by scripts/sync-capabilities.ts
 * DO NOT EDIT MANUALLY — edit the source in lib/capabilities/<id>.ts instead.
 */

import { FirebaseCapabilityDoc } from './types';

const calendarCapability: FirebaseCapabilityDoc = {
    id: "calendar",
    displayName: "Calendar",
    minVersion: "1.0.0",
    docs: `📅 CALENDAR (AppacadabraCalendar)
- \`createEvent(title, desc, startMs, endMs, callback)\`
- \`createEventWithReminder(title, desc, startMs, endMs, minutes, callback)\`
- \`getEvents(startMs, endMs, callback)\` - Callback: \`callback(success, data)\`
    - **data** is an already-parsed Array (do NOT JSON.parse): \`[{id, title, startDate, endDate, allDay, location, notes, calendarId, calendarName, attendees: [{name, email, status, isCurrentUser}]}, ...]\`
- \`deleteEvent(eventId, callback)\`
    - **Return**: "Event deleted" (string)
- **Return for create**: "Calendar opened" (string)`,
};

export default calendarCapability;
