/**
 * AUTO-GENERATED by scripts/sync-capabilities.ts
 * DO NOT EDIT MANUALLY — edit the source in lib/capabilities/<id>.ts instead.
 */

import { FirebaseCapabilityDoc } from './types';

const cameraCapability: FirebaseCapabilityDoc = {
    id: "camera",
    displayName: "Camera",
    minVersion: "1.0.0",
    docs: `📸 CAMERA (AppacadabraCamera)
- \`takePhoto(callback)\` - Take a photo using the device camera
    - **Callback Data (string)**: Complete DataURI string (\`data:image/jpeg;base64,...\`). Use directly as img src (do NOT append prefixes manually).
    - **Example**: \`AppacadabraCamera.takePhoto("onPhotoTaken")\`
- \`recordVideo(options, callback)\` - Record a video using the device camera
    - **options** (object, optional): \`{ maxDuration?: number (seconds, default 60, max 300), quality?: "high"|"low" }\`
    - **Callback Data (string)**: Complete DataURI string (\`data:video/mp4;base64,...\`). Use with \`AppacadabraAI.fromVideo(uri).generate(...)\`.
    - **Example**: \`AppacadabraCamera.recordVideo({ maxDuration: 30 }, "onVideoRecorded")\`
    - **Example (no options)**: \`AppacadabraCamera.recordVideo("onVideoRecorded")\`
- \`playVideo(base64, options, callback)\` - Play a video from base64 data
    - **options** (object, optional): \`{ mimeType?: "video/mp4"|"video/webm" }\`
    - **Return**: "Playing" (string)
    - **Example**: \`AppacadabraCamera.playVideo(videoBase64, "onPlaying")\`
- \`stopPlaying(callback)\` - Stop current video playback
    - **Return**: "Stopped" (string)
- \`isPlaying(callback)\` - Check if video is currently playing
    - **Return**: "true" or "false" (string)
- \`scan(callback)\` - Open QR/Barcode scanner overlay
    - **Callback Data (string)**: Scanned content string
    - **Example**: \`AppacadabraCamera.scan("onCodeScanned")\``,
};

export default cameraCapability;
