/**
 * AUTO-GENERATED by scripts/sync-capability-docs.ts
 * DO NOT EDIT MANUALLY — edit the source in lib/capabilities/<id>.ts instead.
 */

import { FirebaseCapabilityDoc } from './types';

const clipboardCapability: FirebaseCapabilityDoc = {
    id: "clipboard",
    displayName: "Clipboard",
    minVersion: "1.0.0",
    docs: `📋 CLIPBOARD (AppacadabraClipboard)
- \`setString(text)\` - Copy text to clipboard
- \`getString(callback)\` - Get text from clipboard
    - **Return**: Clipboard text (string)`,
};

export default clipboardCapability;
