/**
 * AUTO-GENERATED by scripts/sync-capabilities.ts
 * DO NOT EDIT MANUALLY — edit the source in lib/capabilities/<id>.ts instead.
 */

import { FirebaseCapabilityDoc } from './types';

const contactsCapability: FirebaseCapabilityDoc = {
    id: "contacts",
    displayName: "Contacts",
    minVersion: "1.0.0",
    docs: `📇 CONTACTS (AppacadabraContacts): prefer search/update
- \`search(query, callback)\`
    - **Return JSON**: Same array format as getAll.
- \`update(contactObj, callback)\` - Opens native edit form with pre-filled data
    - **Return**: Contact ID (string) or "Contact form presented"
- \`add(contactObj, callback)\` - Opens native add form with pre-filled data
    - **Return**: "Contact form presented"

**contactObj structure** (Native Expo Contacts format):
\`\`\`javascript
{
  id: "string",           // REQUIRED for update only
  name: "string",         // Full name
  firstName: "string",    // First name
  lastName: "string",     // Last name
  company: "string",      // Company name
  jobTitle: "string",     // Job title
  department: "string",   // Department
  nickname: "string",     // Nickname
  note: "string",         // Notes
  phoneNumbers: [         // Array of phones
    { number: "string", label: "mobile|home|work" }
  ],
  emails: [               // Array of emails
    { email: "string", label: "work|home" }
  ],
  addresses: [            // Array of addresses
    {
      street: "string",
      city: "string",
      region: "string", // State/Region
      postalCode: "string", // Zip
      country: "string",
      label: "home|work"
    }
  ],
  birthday: { year: number, month: number, day: number }, // Object
  urlAddresses: [         // Websites
    { url: "string", label: "homepage" }
  ]
}
\`\`\``,
};

export default contactsCapability;
