/**
 * AUTO-GENERATED by scripts/sync-capabilities.ts
 * DO NOT EDIT MANUALLY — edit the source in lib/capabilities/<id>.ts instead.
 */

import { FirebaseCapabilityDoc } from './types';

const deviceCapability: FirebaseCapabilityDoc = {
    id: "device",
    displayName: "Device",
    minVersion: "1.0.0",
    docs: `📱 DEVICE (AppacadabraDevice)
- \`vibrate(pattern)\` - Vibrate device (number or array of numbers). **No callback**.
- \`cancelVibration()\` - Stop vibration. **No callback**.
- \`getBatteryLevel(callback)\` - Get battery level.
    - **Callback Data**: Battery level (number 0.0 - 1.0)
- \`isCharging(callback)\` - Check if charging.
    - **Callback Data**: Charging status (boolean)
- \`isOnline(callback)\` - Check if online.
    - **Callback Data**: \`true\` or \`false\` (boolean)
- \`getNetworkType(callback)\` - Get connection info.
    - **Callback Data**: Connection type string ('wifi', 'cellular', 'none', 'unknown')
- \`language\` - **Property** (string). Device language (e.g. "en-US")
- \`userAgent\` - **Property** (string). User agent string
- \`openBrowser(url)\` - Open URL in system browser`,
};

export default deviceCapability;
