/**
 * AUTO-GENERATED by scripts/sync-capabilities.ts
 * DO NOT EDIT MANUALLY — edit the source in lib/capabilities/<id>.ts instead.
 */

import { FirebaseCapabilityDoc } from './types';

const docsCapability: FirebaseCapabilityDoc = {
    id: "docs",
    displayName: "Docs",
    minVersion: "1.0.0",
    docs: `📄 DOCS (AppacadabraDocs) — Google Sign-In required (consent shown on first use only)
⚠️ **Restricted access:** \`getDoc()\`, \`appendText()\`, \`setDoc()\` and \`watchDoc()\` work **only with documents created by this app via \`createDoc()\`**. Existing Google Docs from the user cannot be accessed — not even documents they created manually in Google Drive. If the user mentions an existing document, explain that the app can only access files it generated itself and offer to create a new one.

**Basic operations:**
- \`createDoc(title, content, callback)\` — Creates a Google Doc with optional markdown content
  - \`content\`: optional markdown string. Supported: \`# H1\`, \`## H2\`, \`### H3\`, \`- bullet\`, \`**bold**\`, \`*italic*\`, plain paragraphs
  - **Callback data**: \`{ docId, url }\`
- \`getDoc(docId, callback)\` — Reads document content as markdown
  - **Callback data**: \`{ title, content }\` (content is a markdown string — headings, bullets, bold, italic preserved)
- \`appendText(docId, text, callback)\` — Appends markdown text to the end of the document
  - **Callback data**: \`{ docId }\`
- \`setDoc(docId, content, callback)\` — **Replaces** the entire document body with new markdown content
  - Use when you want to rewrite or clear the document (e.g. save a new version of a report)
  - After success, the active watcher (if any) skips the next poll to avoid a spurious change event
  - Offline: write is queued and auto-replayed; callback receives \`{ queued: true }\`
  - **Callback data**: \`{ docId }\` or \`{ queued: true }\`
- \`convert(from, to, content, callbackName)\` — Converts between formats (all async, callback-based)
  - \`from\`: \`'markdown'\` | \`'html'\`
  - \`to\`: \`'html'\` | \`'markdown'\` | \`'pdf'\`
  - **Callback data**: string — HTML, markdown, or base64 PDF
  - For \`to: 'pdf'\`: use \`AppacadabraShare.shareFile(base64, 'application/pdf', 'doc.pdf', cb)\`
  - Markdown supported: H1–H3, bullets, bold, italic, tables, code blocks, blockquotes, \`---\` hr

**Native sync mode (recommended for documents edited externally):**

Use \`watchDoc\` in spells like "collaborative editor" or "shared log" where the document may be edited from outside (another user or device). The capability detects changes and fires the callback automatically.

- \`watchDoc(docId, intervalMs, callbackName)\` — Starts polling for external changes
  - Fires **immediately** with current content (\`initial: true\`), then only when title or content changes
  - \`intervalMs\`: polling interval in ms (e.g. \`10000\` = every 10 s)
  - **Callback data (ok, data)**:
    - \`data.title\`: document title
    - \`data.content\`: full document content as markdown string
    - \`data.initial\`: \`true\` on first call — use to populate the editor
    - \`data.cached\`: \`true\` when offline and data comes from last successful read
  - Offline behaviour: fires with \`{ cached: true, ...lastKnownData }\`; if no cache: \`ok=false, { offline: true }\`
- \`stopWatchDoc(docId, callbackName)\` — Stops polling
  - **Callback data**: \`{ stopped: true }\`

**⚠️ RULE:** Use \`watchDoc\` + \`setDoc\` for collaborative editing. Use \`appendText\` + \`getDoc\` for insert-only docs (journals, logs). Do not save \`lastSyncTimestamp\` in localStorage — diffing is handled by the capability.

**Usage (native sync):**
\`\`\`js
// 1. On open: loads current content (or offline cache)
AppacadabraDocs.watchDoc(localStorage.getItem('docId'), 10000, 'onDocChanged');
window.onDocChanged = function(ok, data) {
  if (!ok) { if (data.offline) showBanner('No connection'); return; }
  if (data.cached) showBanner('Offline content');
  editor.setValue(data.content);   // data.initial = true on first call
};

// 2. Save a full new version (queued offline automatically)
AppacadabraDocs.setDoc(localStorage.getItem('docId'), editor.getValue(), 'onSaved');
window.onSaved = function(ok, data) {
  if (data.queued) showBanner('Saving when connection returns');
};

// 3. Append only (without rewriting everything)
AppacadabraDocs.appendText(localStorage.getItem('docId'), '\\\\n## New Section\\\\nContent', 'done');

// 4. Stop when closing the screen
AppacadabraDocs.stopWatchDoc(localStorage.getItem('docId'), 'done');

// 5. WYSIWYG editor pattern (read → display editable → save back)
AppacadabraDocs.watchDoc(localStorage.getItem('docId'), 10000, 'onDoc');
const editor = document.getElementById('editor');
editor.contentEditable = 'true';
window.onDoc = function(ok, data) {
  if (!ok) return;
  AppacadabraDocs.convert('markdown', 'html', data.content, 'onRendered');
};
window.onRendered = function(ok, html) { editor.innerHTML = html; };
function save() {
  AppacadabraDocs.convert('html', 'markdown', editor.innerHTML, 'onConverted');
}
window.onConverted = function(ok, md) {
  AppacadabraDocs.setDoc(localStorage.getItem('docId'), md, 'onSaved');
};
\`\`\``,
};

export default docsCapability;
