/**
 * AUTO-GENERATED by scripts/sync-capability-docs.ts
 * DO NOT EDIT MANUALLY — edit the source in lib/capabilities/<id>.ts instead.
 */

import { FirebaseCapabilityDoc } from './types';

const docsCapability: FirebaseCapabilityDoc = {
    id: "docs",
    displayName: "Docs",
    minVersion: "1.0.0",
    docs: `📄 DOCS (AppacadabraDocs) — Google Sign-In required (consent shown on first use only)
- \`createDoc(title, content, callback)\` — Creates a Google Doc with optional markdown content
  - \`content\`: optional markdown string. Supported: \`# H1\`, \`## H2\`, \`### H3\`, \`- bullet\`, \`**bold**\`, \`*italic*\`, plain paragraphs
  - **Callback data**: \`{ docId, url }\`
- \`getDoc(docId, callback)\` — Reads document content as markdown (round-trip with \`createDoc\`)
  - **Callback data**: \`{ title, content }\` (content is markdown string — headings, bullets, bold, italic preserved)
- \`appendText(docId, text, callback)\` — Appends markdown text to the end of the document
  - **Callback data**: \`{ docId }\`
- \`generatePDF(content, type, callback)\` — Converts markdown or HTML to a styled PDF (base64)
  - \`content\`: markdown string or full HTML document
  - \`type\`: \`'markdown'\` (default, auto-styled) | \`'html'\` (used as-is)
  - **Callback data (string)**: Base64-encoded PDF — use with \`AppacadabraShare.shareFile(base64, 'application/pdf', 'doc.pdf', cb)\`
- **Usage**:
  \`\`\`js
  AppacadabraDocs.createDoc("Patient Report",
    \`# Maria Silva
## Personal Info
**Date:** 2026-03-26
**Diagnosis:** Flu

## Symptoms
- Fever
- Cough
- Fatigue\`,
    "onDocReady");
  window.onDocReady = function(ok, data) {
    if (!ok) return;
    localStorage.setItem('reportDocId', data.docId);
    showLink(data.url);
  };
  AppacadabraDocs.appendText(localStorage.getItem('reportDocId'),
    "\\\\n## Follow-up\\\\nScheduled for **2026-04-01**", "onAppended");
  \`\`\``,
};

export default docsCapability;
