/**
 * AUTO-GENERATED by scripts/sync-capabilities.ts
 * DO NOT EDIT MANUALLY — edit the source in lib/capabilities/<id>.ts instead.
 */

import { FirebaseCapabilityDoc } from './types';

const formsCapability: FirebaseCapabilityDoc = {
    id: "forms",
    displayName: "Forms",
    minVersion: "1.0.0",
    docs: `📋 FORMS (AppacadabraForms) — Google Sign-In required (consent shown on first use only)
⚠️ **Restricted access:** \`getResponses()\`, \`updateForm()\` and \`watchResponses()\` work **only with forms created by this app via \`createForm()\`**. External forms cannot be accessed for two reasons: (1) OAuth scope restriction \`drive.file\`; (2) the question mapping is stored internally at creation time and does not exist for external forms. Never suggest the user use an existing Google Form.

**Basic operations:**
- \`createForm(title, questions[], callback)\` — Creates a Google Form
  - \`questions\`: \`[{ type: "text"|"paragraph"|"radio"|"checkbox"|"dropdown", title: "...", options?: ["..."] }]\`
  - **Callback data**: \`{ formId, shareUrl }\`
- \`updateForm(formId, title, questions[], callback)\` — Replaces form questions; same shareUrl is preserved
  - **Callback data**: \`{ formId, shareUrl }\`
- \`getResponses(formId, callback)\` — Fetches all responses with human-readable answer labels
  - **Callback data**: \`{ responses: [{ responseId, submitTime, answers: { "Question title": "answer" } }] }\`

**Native sync mode (recommended — receives new responses in real time):**

Use \`watchResponses\` in dashboard spells that need to display responses as they arrive, without the user having to reload the page. The capability detects new responseIds and fires the callback only when there are new entries.

- \`watchResponses(formId, intervalMs, callbackName)\` — Starts polling for new responses
  - Fires **immediately** with all current responses (\`initial: true\`), then only when new ones arrive
  - \`intervalMs\`: polling interval in ms (e.g. \`15000\` = every 15 s)
  - **Callback data (ok, data)**:
    - \`data.responses\`: all responses (use on \`initial: true\` to populate the table)
    - \`data.newResponses\`: only the responses added since the last poll (use to append new rows)
    - \`data.initial\`: \`true\` on first call — render everything; subsequent calls only when new responses exist
    - \`data.cached\`: \`true\` when offline and data comes from last successful read
  - Offline behaviour: fires with \`{ cached: true, ...lastKnownData }\`; if no cache: \`ok=false, { offline: true }\`
- \`stopWatchResponses(formId, callbackName)\` — Stops polling
  - **Callback data**: \`{ stopped: true }\`

**Question types** (all support \`required: true\` and optional \`title\`):
  - \`"text"\` — short text answer: \`{ type: "text", title: "Full name" }\`
  - \`"paragraph"\` — long text answer: \`{ type: "paragraph", title: "Describe your symptoms" }\`
  - \`"radio"\` — pick exactly one: \`{ type: "radio", title: "Reason for visit", options: ["Consultation", "Follow-up", "Emergency"] }\`
  - \`"checkbox"\` — pick one or more: \`{ type: "checkbox", title: "Current symptoms", options: ["Fever", "Cough", "Fatigue"] }\`
  - \`"dropdown"\` — pick one from a list: \`{ type: "dropdown", title: "Preferred time", options: ["Morning", "Afternoon", "Evening"] }\`
  - Add \`shuffle: true\` to any \`radio\`/\`checkbox\`/\`dropdown\` to randomise option order
  - \`"date"\` — date picker: \`{ type: "date", title: "Date of birth" }\`
  - \`"datetime"\` — date + time picker: \`{ type: "datetime", title: "Appointment date and time" }\`
  - \`"time"\` — specific time of day: \`{ type: "time", title: "Preferred appointment time" }\`
  - \`"duration"\` — elapsed time (hh:mm:ss): \`{ type: "duration", title: "How long did symptoms last?" }\`
  - \`"scale"\` — numeric range (\`low\` and \`high\` required): \`{ type: "scale", title: "Pain level", low: 1, high: 10, lowLabel: "No pain", highLabel: "Worst pain" }\`
  - \`"rating"\` — icon-based rating: \`{ type: "rating", title: "Rate your experience", level: 5, icon: "star" }\` — \`icon\`: \`"star"\` | \`"heart"\` | \`"thumb"\` (default: \`"star"\`, default level: \`5\`)

**⚠️ RULE:** Use \`watchResponses\` instead of \`getResponses\` in any spell that needs to show live responses. Do not use a manual \`setInterval\` in the spell — polling is handled by the capability.

**Usage (native sync):**
\`\`\`js
// 1. On open: loads existing responses and listens for new ones
AppacadabraForms.watchResponses(localStorage.getItem('formId'), 15000, 'onResponses');
window.onResponses = function(ok, data) {
  if (!ok) { if (data.offline) showBanner('No connection'); return; }
  if (data.cached) showBanner('Offline data');
  if (data.initial) renderAll(data.responses);        // first call: render everything
  else data.newResponses.forEach(r => addRow(r));     // subsequent calls: only new ones
};

// 2. Stop when closing the screen
AppacadabraForms.stopWatchResponses(localStorage.getItem('formId'), 'done');
\`\`\``,
};

export default formsCapability;
