/**
 * AUTO-GENERATED by scripts/sync-capabilities.ts
 * DO NOT EDIT MANUALLY — edit the source in lib/capabilities/<id>.ts instead.
 */

import { FirebaseCapabilityDoc } from './types';

const formsCapability: FirebaseCapabilityDoc = {
    id: "forms",
    displayName: "Forms",
    minVersion: "1.0.0",
    docs: `📋 FORMS (AppacadabraForms) — Google Sign-In required (consent shown on first use only)
⚠️ **Acesso restrito:** \`getResponses()\` e \`updateForm()\` funcionam **apenas com formulários criados por este app via \`createForm()\`**. Formulários externos não podem ser acessados por duas razões: (1) restrição de escopo OAuth \`drive.file\`; (2) o mapeamento de perguntas é armazenado internamente no momento da criação e não existe para formulários externos. Nunca sugira ao usuário usar um formulário Google existente.
- \`createForm(title, questions[], callback)\` — Creates a Google Form
  - \`questions\`: \`[{ type: "text"|"paragraph"|"radio"|"checkbox"|"dropdown", title: "...", options?: ["..."] }]\`
  - **Callback data**: \`{ formId, shareUrl }\`
- \`updateForm(formId, title, questions[], callback)\` — Replaces form questions; same shareUrl is preserved
  - **Callback data**: \`{ formId, shareUrl }\`
- \`getResponses(formId, callback)\` — Fetches all responses with human-readable answer labels
  - **Callback data**: \`{ responses: [{ responseId, submitTime, answers: { "Question title": "answer" } }] }\`
  - Question title mapping and history preservation are handled automatically by the bridge
- **Question types** (all support \`required: true\` and optional \`title\`):
  - \`"text"\` — short text answer: \`{ type: "text", title: "Full name" }\`
  - \`"paragraph"\` — long text answer: \`{ type: "paragraph", title: "Describe your symptoms" }\`
  - \`"radio"\` — pick exactly one: \`{ type: "radio", title: "Reason for visit", options: ["Consultation", "Follow-up", "Emergency"] }\`
  - \`"checkbox"\` — pick one or more: \`{ type: "checkbox", title: "Current symptoms", options: ["Fever", "Cough", "Fatigue"] }\`
  - \`"dropdown"\` — pick one from a list: \`{ type: "dropdown", title: "Preferred time", options: ["Morning", "Afternoon", "Evening"] }\`
  - Add \`shuffle: true\` to any \`radio\`/\`checkbox\`/\`dropdown\` to randomise option order
  - \`"date"\` — date picker: \`{ type: "date", title: "Date of birth" }\`
  - \`"datetime"\` — date + time picker: \`{ type: "datetime", title: "Appointment date and time" }\`
  - \`"time"\` — specific time of day: \`{ type: "time", title: "Preferred appointment time" }\`
  - \`"duration"\` — elapsed time (hh:mm:ss): \`{ type: "duration", title: "How long did symptoms last?" }\`
  - \`"scale"\` — numeric range (\`low\` and \`high\` required): \`{ type: "scale", title: "Pain level", low: 1, high: 10, lowLabel: "No pain", highLabel: "Worst pain" }\`
  - \`"rating"\` — icon-based rating: \`{ type: "rating", title: "Rate your experience", level: 5, icon: "star" }\` — \`icon\`: \`"star"\` | \`"heart"\` | \`"thumb"\` (default: \`"star"\`, default level: \`5\`)
- **Usage**:
  \`\`\`js
  AppacadabraForms.createForm("Patient Intake", [
    { type: "text", title: "Full name" },
    { type: "text", title: "Date of birth" },
    { type: "radio", title: "Reason for visit", options: ["Consultation", "Follow-up", "Emergency"] },
    { type: "checkbox", title: "Current symptoms", options: ["Fever", "Cough", "Fatigue", "None"] },
    { type: "paragraph", title: "Additional notes" }
  ], "onFormReady");
  window.onFormReady = function(ok, data) {
    if (!ok) return;
    localStorage.setItem('formId', data.formId);
    showShareLink(data.shareUrl); // send this link to the patient
  };

  AppacadabraForms.getResponses(localStorage.getItem('formId'), "onResponses");
  window.onResponses = function(ok, data) {
    if (ok) displayResponses(data.responses); // answers[title] always works, even for edited forms
  };
  \`\`\``,
};

export default formsCapability;
