/**
 * AUTO-GENERATED by scripts/sync-capabilities.ts
 * DO NOT EDIT MANUALLY — edit the source in lib/capabilities/<id>.ts instead.
 */

import { FirebaseCapabilityDoc } from './types';

const healthCapability: FirebaseCapabilityDoc = {
    id: "health",
    displayName: "Health",
    minVersion: "2.0.0",
    docs: `💪 HEALTH (AppacadabraHealth)
- \`getSteps(startMs, endMs, callback)\` - Get step count
    - **Return**: JSON Object: \`{ "totalSteps": number, "records": [{ "startTime": "ISO String", "endTime": "ISO String", "count": number }] }\`
- \`getHeartRate(startMs, endMs, callback)\` - Get heart rate
    - **Return**: JSON Array of objects: \`[{ "startTime": "ISO String", "endTime": "ISO String", "samples": [{ "time": "ISO String", "beatsPerMinute": number }] }]\`
- \`getExercise(startMs, endMs, callback)\` - Get exercise sessions. **Crucial**:
    - **Return**: JSON Array: \`[{ "startTime": "ISO", "endTime": "ISO", "exerciseTypeName": "ROWING"|"WALKING"|..., "exerciseType": number, "title": string|null (often null! use typeName), "notes": string|null, "metadata": {...} }]\`
    - **Note**: \`title\` is often null. Display \`exerciseTypeName\` as label. \`exerciseType\` 46 is "ROWING". Ignore internal metadata.
- \`getSleep(startMs, endMs, callback)\` - Get sleep sessions
    - **Return**: JSON Array of objects: \`[{ "startTime": "ISO String", "endTime": "ISO String", "title": string|null, "notes": string|null, "stages": [{ "startTime": "ISO String", "endTime": "ISO String", "stage": "AWAKE"|"LIGHT"|"DEEP"|"REM"|"UNKNOWN" }] }]\`
- \`getCalories(startMs, endMs, callback)\` - Get calories burned (Active + Basal)
    - **Return**: JSON Object: \`{ "totalCalories": number, "records": [{ "startTime": "ISO", "endTime": "ISO", "energy": { "inKilocalories": number } }] }\``,
};

export default healthCapability;
