/**
 * AUTO-GENERATED by scripts/sync-capabilities.ts
 * DO NOT EDIT MANUALLY — edit the source in lib/capabilities/<id>.ts instead.
 */

import { SYSTEM_PREAMBLE } from '../prompts';
import { FirebaseCapabilityDoc } from './types';

import clipboardCapability from './clipboard';
import shareCapability from './share';
import screenCapability from './screen';
import deviceCapability from './device';
import calendarCapability from './calendar';
import notifyCapability from './notify';
import healthCapability from './health';
import contactsCapability from './contacts';
import sensorsCapability from './sensors';
import uiCapability from './ui';
import cameraCapability from './camera';
import audioCapability from './audio';
import formsCapability from './forms';
import docsCapability from './docs';
import sheetsCapability from './sheets';
import aiCapability from './ai';

export const ALL_CAPABILITIES: FirebaseCapabilityDoc[] = [
    clipboardCapability,
    shareCapability,
    screenCapability,
    deviceCapability,
    calendarCapability,
    notifyCapability,
    healthCapability,
    contactsCapability,
    sensorsCapability,
    uiCapability,
    cameraCapability,
    audioCapability,
    formsCapability,
    docsCapability,
    sheetsCapability,
    aiCapability,
];

/** Returns true if appVersion >= minVersion (simple semver comparison). */
export function versionGte(appVersion: string, minVersion: string): boolean {
    const parse = (v: string) => v.split('.').map(n => parseInt(n, 10) || 0);
    const [maj1, min1, pat1] = parse(appVersion);
    const [maj2, min2, pat2] = parse(minVersion);
    if (maj1 !== maj2) return maj1 > maj2;
    if (min1 !== min2) return min1 > min2;
    return pat1 >= pat2;
}

/**
 * Builds the system instructions for a given app version.
 * Only capabilities with minVersion <= appVersion are included.
 */
export function buildSystemInstructions(
    appVersion: string,
    caps: FirebaseCapabilityDoc[],
): string {
    if (caps.length === 0) {
        return SYSTEM_PREAMBLE;
    }
    const available = caps.filter(c => versionGte(appVersion, c.minVersion));
    return SYSTEM_PREAMBLE + '\n\n--- API DOCUMENTATION ---\n\n' + available.map(c => c.docs).join('\n\n');
}
