/**
 * AUTO-GENERATED by scripts/sync-capability-docs.ts
 * DO NOT EDIT MANUALLY — edit the source in lib/capabilities/<id>.ts instead.
 */

import { FirebaseCapabilityDoc } from './types';

const notifyCapability: FirebaseCapabilityDoc = {
    id: "notify",
    displayName: "Notify",
    minVersion: "1.0.0",
    docs: `🔔 NOTIFICATION (AppacadabraNotify) **Native Protection**: Auto-deduplicates identical title+body. Max 10 per app (notifications + alarms combined). Use \`id\` to update existing notification.
- \`showNow(title, msg, callback)\` - Show notification immediately
    - **Return**: Notification ID (string)
- \`schedule(title, msg, delayMinutes, callback, id?)\` - Schedule after delay
    - **Return**: Notification ID (string)
- \`scheduleAt(title, msg, timeMs, callback, id?)\` - Schedule at specific time
    - **Return**: Notification ID (string)
- \`alarm(title, msg, delayMinutes, callback, id?)\` - Schedule alarm after delay (rings even on silent)
    - **Return**: Alarm ID (string)
- \`alarmAt(title, msg, timeMs, callback, id?)\` - Schedule alarm at specific time (rings even on silent)
    - **Return**: Alarm ID (string)
- \`getScheduled(callback)\` - List pending notifications and alarms
    - **Return**: JSON \`[{id, title, body, trigger: { type: "timeInterval"|"date", value: number }, isAlarm: boolean}]\` (value is seconds for interval, or timestamp for date)
- \`cancel(id, callback)\` - Cancel notification or alarm by ID
    - **Return**: "Cancelled" (string)
- \`cancelAll(callback)\` - Cancel all notifications and alarms from this app
    - **Return**: "All cancelled" (string)
- \`alert(message)\` - Show custom alert dialog (Promise<void>)
- \`confirm(message)\` - Show custom confirm dialog (Promise<boolean>)
- \`prompt(message, defaultValue)\` - Show custom prompt dialog (Promise<string|null>)`,
};

export default notifyCapability;
