/**
 * AUTO-GENERATED by scripts/sync-capability-docs.ts
 * DO NOT EDIT MANUALLY — edit the source in lib/capabilities/<id>.ts instead.
 */

import { FirebaseCapabilityDoc } from './types';

const screenCapability: FirebaseCapabilityDoc = {
    id: "screen",
    displayName: "Screen",
    minVersion: "1.0.0",
    docs: `🎨 SCREEN (AppacadabraScreen)
- \`print()\` - Open native print dialog
- \`capture(callback)\` - Capture screenshot of current view
    - **Callback Data (string)**: Base64 encoded PNG image
    - **Example**: \`AppacadabraScreen.capture("onScreenshotTaken")\``,
};

export default screenCapability;
