/**
 * AUTO-GENERATED by scripts/sync-capabilities.ts
 * DO NOT EDIT MANUALLY — edit the source in lib/capabilities/<id>.ts instead.
 */

import { FirebaseCapabilityDoc } from './types';

const sensorsCapability: FirebaseCapabilityDoc = {
    id: "sensors",
    displayName: "Sensors",
    minVersion: "1.0.0",
    docs: ` SENSORS (AppacadabraSensors)
- **IMPORTANT**: All sensor callbacks must be GLOBAL function names (strings).
- \`startAccelerometer(intervalMs, callbackName)\`
    - **Callback**: Global function name (string).
    - **Data**: \`{ "x": number, "y": number, "z": number }\` (in Gs)
- \`startGyroscope(intervalMs, callbackName)\`
    - **Data**: \`{ "x": number, "y": number, "z": number }\` (rotation rate in rad/s)
- \`startCompass(intervalMs, callbackName)\`
    - **Data**: \`{ "heading": number, "x": number, "y": number, "z": number }\`
    - **Note**: \`heading\` is relative to North (0-360).
- \`startPedometer(callbackName)\`
    - **Data**: \`{ "steps": number }\`
    - **Tip**: Takes 10-20 steps to start triggering events.
- \`startSpeedometer(callbackName)\`
    - **Data**: \`{ "speed": number }\` (in km/h)
- \`startGPS(callbackName)\`
    - **Data**: \`{ "latitude": number, "longitude": number, "altitude": number, "heading": number, "speed": number }\`
- \`stopAll()\`
    - **Note**: Stops ALL active sensors. ALWAYS call this when leaving the screen or pausing.`,
};

export default sensorsCapability;
