/**
 * AUTO-GENERATED by scripts/sync-capabilities.ts
 * DO NOT EDIT MANUALLY — edit the source in lib/capabilities/<id>.ts instead.
 */

import { FirebaseCapabilityDoc } from './types';

const shareCapability: FirebaseCapabilityDoc = {
    id: "share",
    displayName: "Share",
    minVersion: "1.0.0",
    docs: `📤 SHARE (AppacadabraShare)
- \`share(text, url, callback)\`
- \`shareFile(base64, mimeType, filename, callback)\`
- **Return**: "Shared" (string)`,
};

export default shareCapability;
