/**
 * AUTO-GENERATED by scripts/sync-capabilities.ts
 * DO NOT EDIT MANUALLY — edit the source in lib/capabilities/<id>.ts instead.
 */

import { FirebaseCapabilityDoc } from './types';

const sheetsCapability: FirebaseCapabilityDoc = {
    id: "sheets",
    displayName: "Sheets",
    minVersion: "1.0.0",
    docs: `📊 SHEETS (AppacadabraSheets) — Google Sign-In required (consent shown on first use only)
- \`createSheet(title, headers[], callback)\` — Creates a Google Spreadsheet
  - \`headers\`: optional column headers written to row 1 (e.g. \`["Name", "Date", "Status"]\`)
  - **Callback data**: \`{ sheetId, url }\`
- \`appendRows(sheetId, rows[][], callback)\` — Appends rows of data
  - \`rows\`: array of arrays e.g. \`[["Alice", "2026-03-26", "Active"], ["Bob", "2026-03-25", "Pending"]]\`
  - **Callback data**: \`{ updatedRows }\` (number of rows added)
- \`getRows(sheetId, callback)\` — Reads all data; first row treated as headers
  - **Callback data**: \`{ headers: ["Name", "Date"], rows: [{ "Name": "Alice", "Date": "2026-03-26" }, ...] }\`
- \`clearRows(sheetId, callback)\` — Clears all data from the sheet
  - **Callback data**: \`{ sheetId }\`
- \`updateCell(sheetId, cell, value, callback)\` — Sets a single cell value (e.g. \`"B3"\`)
  - **Callback data**: \`{ sheetId }\`
- **Usage**:
  \`\`\`js
  AppacadabraSheets.createSheet("Patient Log",
    ["Name", "Date", "Reason", "Status"], "onSheetReady");
  window.onSheetReady = function(ok, data) {
    if (!ok) return;
    localStorage.setItem('logSheetId', data.sheetId);
  };

  // Log a new patient visit
  AppacadabraSheets.appendRows(localStorage.getItem('logSheetId'),
    [["Maria Silva", "2026-03-26", "Consultation", "Completed"]], "onAppended");

  // Read all records
  AppacadabraSheets.getRows(localStorage.getItem('logSheetId'), "onRows");
  window.onRows = function(ok, data) {
    if (ok) renderTable(data.headers, data.rows);
  };
  \`\`\``,
};

export default sheetsCapability;
