/**
 * AUTO-GENERATED by scripts/sync-capabilities.ts
 * DO NOT EDIT MANUALLY — edit the source in lib/capabilities/<id>.ts instead.
 */

import { FirebaseCapabilityDoc } from './types';

const sheetsCapability: FirebaseCapabilityDoc = {
    id: "sheets",
    displayName: "Sheets",
    minVersion: "1.0.0",
    docs: `📊 SHEETS (AppacadabraSheets) — Google Sign-In required (consent shown on first use only)
⚠️ **Restricted access:** \`getRows()\`, \`appendRows()\`, \`watchSheet()\` and \`setRows()\` work **only with spreadsheets created by this app via \`createSheet()\`**. Existing Google Sheets from the user cannot be accessed. If the user wants to use "their sales spreadsheet" or similar, explain the limitation and offer to create a new dedicated spreadsheet inside the app.

**Simple mode (insert-only, no sync):**
- \`createSheet(title, headers[], callback)\` — Creates a Google Spreadsheet
  - \`headers\`: optional column headers written to row 1 (e.g. \`["Name", "Date", "Status"]\`)
  - **Callback data**: \`{ sheetId, url }\`
- \`appendRows(sheetId, rows[][], callback)\` — Appends rows of raw data (string[][])
  - \`rows\`: array of arrays e.g. \`[["Alice", "2026-03-26", "Active"], ["Bob", "2026-03-25", "Pending"]]\`
  - **Callback data**: \`{ updatedRows }\` (number of rows added)
- \`getRows(sheetId, callback)\` — Reads all data; first row treated as headers
  - **Callback data**: \`{ headers: ["Name","Date"], rows: [{ "Name": "Alice", "Date": "2026-03-26" }, ...] }\`

**Native sync mode (recommended — no control columns in the spreadsheet):**

Use \`watchSheet\` + \`setRows\` in spells that need to display or edit data that may be changed externally (by other people or other devices). The capability handles all caching and diff detection — the spell only needs to render and save.

- \`watchSheet(sheetId, intervalMs, callbackName)\` — Starts polling for external changes
  - Fires **immediately** with current data (\`initial: true\`), then only when rows change
  - \`intervalMs\`: polling interval in ms (e.g. \`5000\` = every 5 s)
  - **Callback data (ok, data)**:
    - \`data.rows\`: all current rows as objects \`{ "Name": "Alice", ... }\`
    - \`data.headers\`: column names (string[])
    - \`data.added\`: rows added since last poll (empty on initial)
    - \`data.changed\`: rows modified since last poll (empty on initial)
    - \`data.deleted\`: rows removed since last poll (empty on initial)
    - \`data.initial\`: \`true\` on first call — use to populate the full UI
    - \`data.cached\`: \`true\` when offline and data comes from last successful read
  - Offline behaviour: fires with \`{ cached: true, ...lastKnownData }\`; if no cache ever: \`ok=false, { offline: true }\`
- \`stopWatchSheet(sheetId, callbackName)\` — Stops polling
  - **Callback data**: \`{ stopped: true }\`
- \`setRows(sheetId, rows[], callbackName)\` — Replaces ALL data rows (row objects), keeps headers
  - \`rows\`: \`[{ "Name": "Alice", "Date": "2026-03-26" }, ...]\` — pass \`[]\` to clear data while keeping headers
  - After write, the active watcher skips the next poll to avoid a spurious change event
  - Offline: queued and auto-replayed when connection returns; callback receives \`{ queued: true }\`
  - **Callback data**: \`{ rowsWritten: N }\` or \`{ queued: true }\`

**⚠️ RULE:** Never add control columns (\`__modified_at__\`, \`__sync__\`) to the spreadsheet — diffing is handled by the capability. Use \`appendRows\` + \`getRows\` only for insert-only spells (logs, checklists without editing).

**Usage (native sync):**
\`\`\`js
// 1. watchSheet: full render on initial load, incremental updates after
AppacadabraSheets.watchSheet(localStorage.getItem('sheetId'), 5000, 'onChanged');
window.onChanged = function(ok, data) {
  if (!ok) { if (data.offline) showBanner('No connection'); return; }
  if (data.cached) showBanner('Offline data');
  if (data.initial) {
    renderTable(data.headers, data.rows);   // full render only on first call
  } else {
    // Incremental updates: add/modify/remove rows without re-rendering everything
    data.added.forEach(row => appendRowToTable(row));
    data.changed.forEach(row => updateRowInTable(row));
    data.deleted.forEach(row => removeRowFromTable(row));
  }
};

// 2. setRows: optimistic update — update in-memory state BEFORE saving
function saveRows(rows) {
  state.rows = rows;
  renderTable(state.headers, state.rows);    // update UI immediately (optimistic)
  AppacadabraSheets.setRows(localStorage.getItem('sheetId'), rows, 'onSaved'); // persist to Sheets
  // Note: onChanged will NOT fire after setRows (internal mechanism prevents it)
  // Use localStorage only for app data that does NOT live in the spreadsheet (e.g. sheetId, settings)
}
window.onSaved = function(ok, data) {
  if (data.queued) showBanner('Saving when connection returns');
};

// 3. Stop when closing the screen
AppacadabraSheets.stopWatchSheet(localStorage.getItem('sheetId'), 'done');
\`\`\``,
};

export default sheetsCapability;
