/**
 * Firebase-side capability type.
 *
 * This is a stripped-down view of CapabilityModule — only the fields
 * needed on the server (no WebView JS, no native handlers).
 * Files in this directory are AUTO-GENERATED by scripts/sync-capabilities.ts.
 * Edit the source modules in lib/capabilities/ instead.
 */

export interface FirebaseCapabilityDoc {
    id: string;
    displayName: string;
    /** Minimum app version required for this capability (semver). */
    minVersion: string;
    /** AI documentation block injected into the system instructions. */
    docs: string;
}
