/**
 * AUTO-GENERATED by scripts/sync-capability-docs.ts
 * DO NOT EDIT MANUALLY — edit the source in lib/capabilities/<id>.ts instead.
 */

import { FirebaseCapabilityDoc } from './types';

const uiCapability: FirebaseCapabilityDoc = {
    id: "ui",
    displayName: "UI",
    minVersion: "1.0.0",
    docs: `🎨 UI HELPERS (AppacadabraUI)
- \`showLoader(message?, options?)\` - Show a full-screen loading overlay with a spinner. Options: \`{ color?: string, bg?: string }\`. Defaults: color from \`--color-primary\` CSS var or #6366f1; bg: rgba(255,255,255,0.92). **No callback.**
- \`hideLoader()\` - Hide the loading overlay. **No callback.**
- \`toast(message, type?, options?)\` - Show a brief auto-dismissing message (3s). type: \`'success'\`|\`'error'\`|\`'info'\` (default). Options: \`{ color?: string, duration?: number }\`. Color defaults: success=#10b981, error=#ef4444, info=\`--color-primary\`.
- **Customization example (dark-themed app)**:
  \`\`\`js
  AppacadabraUI.showLoader("Loading...", { color: '#38bdf8', bg: 'rgba(15,23,42,0.92)' });
  AppacadabraUI.toast("Error loading data", "error", { color: '#f87171', duration: 5000 });
  \`\`\`
- **Standard pattern**:
  \`\`\`js
  AppacadabraUI.showLoader("Processing with AI...");
  AppacadabraAI.generate(prompt, "onResult");
  window.onResult = function(success, data) {
      AppacadabraUI.hideLoader();
      if (!success) { AppacadabraUI.toast(data, "error"); return; }
      // handle result...
  };
  \`\`\``,
};

export default uiCapability;
