/**
 * withIosLocalizedInfoPlist
 *
 * Generates `<locale>.lproj/InfoPlist.strings` files for every locale defined in
 * `iosInfoPlistTranslations.js` (mirrors the 17 locales in `lib/i18n.ts`) and
 * wires them into the Xcode project so iOS picks the correct permission strings
 * based on the user's device language. The values in `app.json` → `ios.infoPlist`
 * remain the default fallback for locales not listed here.
 *
 * What it does on `expo prebuild --platform ios`:
 *   1. (withDangerousMod) Writes `ios/Appacadabra/<locale>.lproj/InfoPlist.strings`
 *      for each locale, in UTF-8 with quoted-pair entries Xcode understands.
 *   2. (withXcodeProject) Registers each locale in the project's `knownRegions`,
 *      creates a single `PBXVariantGroup` named "InfoPlist.strings" with one
 *      child PBXFileReference per locale, and adds the variant group to the
 *      main app target's Resources build phase. Idempotent — re-running prebuild
 *      without --clean detects the existing variant group and skips re-creation.
 *
 * Locale → .lproj folder mapping: most i18n.ts codes are a 1:1 match. The
 * exception is `pt` → `pt-BR` (Brazil is the larger Portuguese-speaking market;
 * pt-PT users get the Info.plist default, which already uses Portuguese
 * Portugal phrasing).
 */

const { withDangerousMod, withXcodeProject } = require('@expo/config-plugins');
const fs = require('fs-extra');
const path = require('path');

const TRANSLATIONS = require('./iosInfoPlistTranslations');

const VARIANT_GROUP_NAME = 'InfoPlist.strings';
const STRINGS_FILENAME = 'InfoPlist.strings';

// i18n.ts code → iOS .lproj folder. Keep this single source of truth in sync
// when adding/removing locales in i18n.ts.
const LOCALE_TO_LPROJ = {
  en: 'en',
  pt: 'pt-BR',
  es: 'es',
  fr: 'fr',
  de: 'de',
  it: 'it',
  ja: 'ja',
  zh: 'zh-Hans',
  ko: 'ko',
  ar: 'ar',
  hi: 'hi',
  ru: 'ru',
  tr: 'tr',
  nl: 'nl',
  pl: 'pl',
  vi: 'vi',
  th: 'th',
};

/** Escape a value for a .strings file (backslash, double quote, newline, CR). */
function escapeStringsValue(value) {
  return String(value)
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r');
}

function renderStringsFile(entries) {
  const lines = [
    '/* Auto-generated by plugins/withIosLocalizedInfoPlist.js — do not edit by hand.',
    '   Edit plugins/iosInfoPlistTranslations.js and re-run `npx expo prebuild --platform ios`. */',
    '',
  ];
  for (const [key, value] of Object.entries(entries)) {
    lines.push(`"${key}" = "${escapeStringsValue(value)}";`);
  }
  return lines.join('\n') + '\n';
}

/**
 * Step 1: write `<locale>.lproj/InfoPlist.strings` under the iOS project directory.
 * Path layout matches Xcode's expectation when `sourceTree` is `"<group>"` and
 * the variant group lives at the project root.
 */
const withLocalizedInfoPlistFiles = (config) => {
  return withDangerousMod(config, [
    'ios',
    async (innerConfig) => {
      const platformRoot = innerConfig.modRequest.platformProjectRoot;
      const projectName =
        innerConfig.modRequest.projectName ||
        innerConfig.ios?.bundleIdentifier?.split('.').pop() ||
        'Appacadabra';
      const projectDir = path.join(platformRoot, projectName);

      if (!(await fs.pathExists(projectDir))) {
        console.warn(
          `[withIosLocalizedInfoPlist] iOS project dir not found at ${projectDir}; skipping.`,
        );
        return innerConfig;
      }

      for (const [i18nCode, entries] of Object.entries(TRANSLATIONS)) {
        const lprojName = LOCALE_TO_LPROJ[i18nCode];
        if (!lprojName) {
          console.warn(
            `[withIosLocalizedInfoPlist] No .lproj mapping for "${i18nCode}"; skipping.`,
          );
          continue;
        }
        const lprojDir = path.join(projectDir, `${lprojName}.lproj`);
        await fs.ensureDir(lprojDir);
        await fs.writeFile(
          path.join(lprojDir, STRINGS_FILENAME),
          renderStringsFile(entries),
          'utf8',
        );
      }
      console.log(
        `[withIosLocalizedInfoPlist] Wrote ${Object.keys(TRANSLATIONS).length} ${STRINGS_FILENAME} files.`,
      );
      return innerConfig;
    },
  ]);
};

/**
 * Step 2: wire the .lproj files into project.pbxproj.
 *
 * Strategy:
 *   - Use xcode-node's `addKnownRegion` for each locale (idempotent — internal
 *     `hasKnownRegion` check).
 *   - Look up an existing `PBXVariantGroup` named "InfoPlist.strings". If one
 *     exists we assume a previous run wired it up correctly and only top-up
 *     missing locale children. Otherwise we create the variant group, attach it
 *     under the main project group (Appacadabra/), and add it to the main
 *     target's Resources build phase.
 */
const withLocalizedInfoPlistXcode = (config) => {
  return withXcodeProject(config, (innerConfig) => {
    const xcode = innerConfig.modResults;

    for (const i18nCode of Object.keys(TRANSLATIONS)) {
      const region = LOCALE_TO_LPROJ[i18nCode];
      if (region) xcode.addKnownRegion(region);
    }

    let variantGroupKey = findExistingVariantGroup(xcode, VARIANT_GROUP_NAME);
    let variantGroup;

    if (variantGroupKey) {
      variantGroup = xcode.getPBXVariantGroupByKey(variantGroupKey);
    } else {
      variantGroupKey = xcode.pbxCreateVariantGroup(VARIANT_GROUP_NAME);
      variantGroup = xcode.getPBXVariantGroupByKey(variantGroupKey);

      // Anchor the variant group under the main app group (e.g. "Appacadabra")
      // so it shows up in Xcode's navigator next to Info.plist.
      const projectName =
        innerConfig.modRequest.projectName ||
        innerConfig.ios?.bundleIdentifier?.split('.').pop() ||
        'Appacadabra';
      const mainGroup = xcode.pbxGroupByName(projectName);
      if (mainGroup) {
        const groupKey = xcode.findPBXGroupKey({ name: projectName });
        if (groupKey) {
          xcode.addToPbxGroup({ uuid: variantGroupKey }, groupKey);
        }
      }

      // Wire the variant group into PBXBuildFile + the main target's
      // Resources build phase so the .strings files actually ship in the bundle.
      const buildFileUuid = xcode.generateUuid();
      const buildFileSection = xcode.hash.project.objects.PBXBuildFile;
      buildFileSection[buildFileUuid] = {
        isa: 'PBXBuildFile',
        fileRef: variantGroupKey,
        fileRef_comment: VARIANT_GROUP_NAME,
      };
      buildFileSection[`${buildFileUuid}_comment`] = `${VARIANT_GROUP_NAME} in Resources`;

      addToMainTargetResourcesPhase(xcode, buildFileUuid, VARIANT_GROUP_NAME);
    }

    if (!variantGroup) {
      console.warn(
        '[withIosLocalizedInfoPlist] Could not resolve variant group; skipping child injection.',
      );
      return innerConfig;
    }

    variantGroup.children = variantGroup.children || [];
    const existingChildPaths = new Set(
      variantGroup.children
        .map((c) => {
          const ref = xcode.hash.project.objects.PBXFileReference?.[c.value];
          return ref && typeof ref === 'object' ? ref.path : null;
        })
        .filter(Boolean),
    );

    for (const [i18nCode] of Object.entries(TRANSLATIONS)) {
      const lprojName = LOCALE_TO_LPROJ[i18nCode];
      if (!lprojName) continue;
      const relativePath = `${lprojName}.lproj/${STRINGS_FILENAME}`;
      if (existingChildPaths.has(relativePath)) continue;

      const fileRefUuid = xcode.generateUuid();
      const fileRefSection = xcode.hash.project.objects.PBXFileReference;
      fileRefSection[fileRefUuid] = {
        isa: 'PBXFileReference',
        lastKnownFileType: 'text.plist.strings',
        name: lprojName,
        path: relativePath,
        sourceTree: '"<group>"',
      };
      fileRefSection[`${fileRefUuid}_comment`] = lprojName;
      variantGroup.children.push({ value: fileRefUuid, comment: lprojName });
    }

    console.log(
      `[withIosLocalizedInfoPlist] Variant group has ${variantGroup.children.length} locales wired.`,
    );
    return innerConfig;
  });
};

function findExistingVariantGroup(xcode, name) {
  const section = xcode.hash.project.objects.PBXVariantGroup;
  if (!section) return null;
  for (const key of Object.keys(section)) {
    if (key.endsWith('_comment')) continue;
    const entry = section[key];
    if (
      entry &&
      typeof entry === 'object' &&
      (entry.name === name || entry.name === `"${name}"` || entry.path === name)
    ) {
      return key;
    }
  }
  return null;
}

/**
 * Insert a PBXBuildFile UUID into the main app target's PBXResourcesBuildPhase.
 * "Main app target" = the first PBXNativeTarget with productType
 * `"com.apple.product-type.application"`.
 */
function addToMainTargetResourcesPhase(xcode, buildFileUuid, comment) {
  const nativeTargets = xcode.hash.project.objects.PBXNativeTarget;
  if (!nativeTargets) return;

  let mainTargetUuid = null;
  for (const key of Object.keys(nativeTargets)) {
    if (key.endsWith('_comment')) continue;
    const t = nativeTargets[key];
    if (!t || typeof t !== 'object') continue;
    const productType = t.productType ? String(t.productType).replace(/"/g, '') : '';
    if (productType === 'com.apple.product-type.application') {
      mainTargetUuid = key;
      break;
    }
  }
  if (!mainTargetUuid) return;

  const target = nativeTargets[mainTargetUuid];
  const phases = target.buildPhases || [];
  const resourcesPhases = xcode.hash.project.objects.PBXResourcesBuildPhase;
  if (!resourcesPhases) return;

  for (const phaseRef of phases) {
    const phase = resourcesPhases[phaseRef.value];
    if (!phase || typeof phase !== 'object') continue;
    phase.files = phase.files || [];
    phase.files.push({ value: buildFileUuid, comment: `${comment} in Resources` });
    return;
  }
}

const withIosLocalizedInfoPlist = (config) => {
  config = withLocalizedInfoPlistFiles(config);
  config = withLocalizedInfoPlistXcode(config);
  return config;
};

module.exports = withIosLocalizedInfoPlist;
