/**
 * sync-capability-docs.ts
 *
 * Extracts { id, displayName, minVersion, docs } from every capability module
 * in lib/capabilities/ by statically parsing the TypeScript source files.
 * This avoids the need to execute native RN/Expo modules at build time.
 *
 * Run:  npm run sync-capabilities
 *
 * Generated files are committed to git — Firebase deploy is self-contained.
 */

import * as path from 'path';
import * as fs from 'fs';

const LIB_CAPS_DIR = path.resolve(__dirname, '../lib/capabilities');
const CAPS_DIR = path.resolve(__dirname, '../firebase/functions/src/capabilities');
const APP_JSON_PATH = path.resolve(__dirname, '../app.json');
const MANIFEST_PATH = path.resolve(__dirname, '../android/app/src/main/AndroidManifest.xml');

/** Permissions not owned by any capability — script never touches these. */
const SYSTEM_PERMISSIONS = new Set([
    'android.permission.INTERNET',
    'android.permission.SYSTEM_ALERT_WINDOW',
    'android.permission.USE_BIOMETRIC',
    'android.permission.USE_FINGERPRINT',
    'android.permission.READ_EXTERNAL_STORAGE',
    'android.permission.WRITE_EXTERNAL_STORAGE',
    'com.android.vending.BILLING',
]);
const BANNER = `/**
 * AUTO-GENERATED by scripts/sync-capability-docs.ts
 * DO NOT EDIT MANUALLY — edit the source in lib/capabilities/<id>.ts instead.
 */`;

interface CapDoc {
    id: string;
    displayName: string;
    minVersion: string;
    docs: string;
}

interface ManifestBlock {
    anchor: string;
    xml: string;
}

const CAPABILITY_MANIFEST_BLOCKS: Record<string, ManifestBlock[]> = {
    health: [
        {
            anchor: '<!-- CAPABILITY:health:queries:anchor -->',
            xml: `  <queries>\n    <package android:name="com.google.android.apps.healthdata"/>\n  </queries>`,
        },
        {
            anchor: '<!-- CAPABILITY:health:mainActivity:anchor -->',
            xml: `      <intent-filter>\n        <action android:name="androidx.health.ACTION_SHOW_PERMISSIONS_RATIONALE"/>\n      </intent-filter>`,
        },
        {
            anchor: '<!-- CAPABILITY:health:application:anchor -->',
            xml: `    <activity-alias android:name="ViewPermissionUsageActivity" android:exported="true" android:targetActivity=".MainActivity" android:permission="android.permission.START_VIEW_PERMISSION_USAGE">\n      <intent-filter>\n        <action android:name="android.intent.action.VIEW_PERMISSION_USAGE"/>\n        <category android:name="android.intent.category.HEALTH_PERMISSIONS"/>\n      </intent-filter>\n    </activity-alias>`,
        },
    ],
};

/**
 * Extracts the value of a simple string field (single or double quotes, or backtick)
 * from a TypeScript source string.
 * Handles:  id: 'foo',  displayName: "Bar",  minVersion: `1.0.0`,
 */
function extractStringField(src: string, field: string): string {
    // Single/double quoted strings
    const reSingleDouble = new RegExp(`\\b${field}\\s*:\\s*(['"])(.*?)\\1`, 's');
    const m1 = reSingleDouble.exec(src);
    if (m1) return m1[2];
    // Backtick strings (no interpolation expected for these fields)
    const reBacktick = new RegExp(`\\b${field}\\s*:\\s*\`(.*?)\``, 's');
    const m2 = reBacktick.exec(src);
    if (m2) return m2[1];
    return '';
}

/**
 * Extracts the docs template literal content.
 * The docs field is always a tagged template literal: docs: `...`,
 * It may contain nested backticks escaped as \`.
 */
function extractDocsField(src: string): string {
    // Find the docs field start
    const docsIdx = src.search(/\bdocs\s*:\s*`/);
    if (docsIdx === -1) return '';

    // Find the opening backtick
    const backtickStart = src.indexOf('`', docsIdx + src.slice(docsIdx).search(/\bdocs\s*:\s*`/) - docsIdx);
    const openIdx = src.indexOf('`', docsIdx);
    if (openIdx === -1) return '';

    // Walk forward to find the closing backtick (accounting for \` escapes)
    let i = openIdx + 1;
    while (i < src.length) {
        if (src[i] === '\\') { i += 2; continue; }
        if (src[i] === '`') break;
        i++;
    }
    return src.slice(openIdx + 1, i)
        .replace(/\\`/g, '`')
        .replace(/\\\$/g, '$');
}

function parseCapabilityFile(filePath: string): CapDoc | null {
    const src = fs.readFileSync(filePath, 'utf-8');

    // Skip non-capability files (types, index, helpers)
    if (!src.includes('CapabilityModule')) return null;
    if (!src.includes('getInjectedJS')) return null;

    const id = extractStringField(src, 'id');
    const displayName = extractStringField(src, 'displayName');
    const minVersion = extractStringField(src, 'minVersion');
    const docs = extractDocsField(src);

    if (!id || !docs) {
        console.warn(`[sync] Warning: could not extract id/docs from ${path.basename(filePath)}`);
        return null;
    }

    return { id, displayName, minVersion, docs };
}

function escapeTemplateLiteral(s: string): string {
    return s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

function generateCapabilityFile(cap: CapDoc): string {
    return `${BANNER}

import { FirebaseCapabilityDoc } from './types';

const ${cap.id}Capability: FirebaseCapabilityDoc = {
    id: ${JSON.stringify(cap.id)},
    displayName: ${JSON.stringify(cap.displayName)},
    minVersion: ${JSON.stringify(cap.minVersion)},
    docs: \`${escapeTemplateLiteral(cap.docs)}\`,
};

export default ${cap.id}Capability;
`;
}

function generateIndexFile(caps: CapDoc[]): string {
    const imports = caps.map(c => `import ${c.id}Capability from './${c.id}';`).join('\n');
    const list = caps.map(c => `    ${c.id}Capability,`).join('\n');
    return `${BANNER}

import { SYSTEM_PREAMBLE } from '../prompts';
import { FirebaseCapabilityDoc } from './types';
${imports ? '\n' + imports : ''}

export const ALL_CAPABILITIES: FirebaseCapabilityDoc[] = [
${list}
];

/** Returns true if appVersion >= minVersion (simple semver comparison). */
export function versionGte(appVersion: string, minVersion: string): boolean {
    const parse = (v: string) => v.split('.').map(n => parseInt(n, 10) || 0);
    const [maj1, min1, pat1] = parse(appVersion);
    const [maj2, min2, pat2] = parse(minVersion);
    if (maj1 !== maj2) return maj1 > maj2;
    if (min1 !== min2) return min1 > min2;
    return pat1 >= pat2;
}

/**
 * Builds the system instructions for a given app version.
 * Only capabilities with minVersion <= appVersion are included.
 */
export function buildSystemInstructions(
    appVersion: string,
    caps: FirebaseCapabilityDoc[],
): string {
    if (caps.length === 0) {
        return SYSTEM_PREAMBLE;
    }
    const available = caps.filter(c => versionGte(appVersion, c.minVersion));
    return SYSTEM_PREAMBLE + '\\n\\n--- API DOCUMENTATION ---\\n\\n' + available.map(c => c.docs).join('\\n\\n');
}
`;
}

/**
 * Parses lib/capabilities/index.ts to find capability IDs in DISABLED_CAPABILITIES
 * that are NOT commented out.
 */
function parseDisabledCapabilities(indexSrc: string): Set<string> {
    const match = indexSrc.match(/DISABLED_CAPABILITIES\s*=\s*new\s+Set<[^>]*>\s*\(\s*\[([\s\S]*?)\]\s*\)/);
    if (!match) return new Set();
    const ids = new Set<string>();
    for (const line of match[1].split('\n')) {
        const trimmed = line.trim();
        if (trimmed.startsWith('//')) continue;
        const m = trimmed.match(/['"]([^'"]+)['"]/);
        if (m) ids.add(m[1]);
    }
    return ids;
}

/**
 * Parses the androidPermissions array from a capability source file.
 */
function parseAndroidPermissions(src: string): string[] {
    const match = src.match(/androidPermissions\s*:\s*\[([\s\S]*?)\]/);
    if (!match) return [];
    return [...match[1].matchAll(/['"]([^'"]+)['"]/g)].map(m => m[1]);
}

/**
 * Syncs Android permissions to app.json and AndroidManifest.xml.
 * - Active capability permissions are added to both files.
 * - Disabled capability permissions are removed from both files.
 * - System permissions (INTERNET, etc.) are never touched.
 */
function syncPermissions(allCapIds: string[], disabledIds: Set<string>): void {
    // Collect permissions from all capability source files
    const activePermissions = new Set<string>();
    const allCapabilityPermissions = new Set<string>();

    for (const id of allCapIds) {
        const srcPath = path.join(LIB_CAPS_DIR, `${id}.ts`);
        if (!fs.existsSync(srcPath)) continue;
        const src = fs.readFileSync(srcPath, 'utf-8');
        const perms = parseAndroidPermissions(src);
        for (const p of perms) {
            allCapabilityPermissions.add(p);
            if (!disabledIds.has(id)) activePermissions.add(p);
        }
    }

    // --- Sync app.json ---
    const appJsonRaw = fs.readFileSync(APP_JSON_PATH, 'utf-8');
    const appJson = JSON.parse(appJsonRaw);
    const currentPerms: string[] = appJson?.expo?.android?.permissions ?? [];

    // Keep system permissions and active capability permissions; drop disabled ones
    const filteredPerms = currentPerms.filter(
        (p: string) => SYSTEM_PERMISSIONS.has(p) || activePermissions.has(p),
    );
    // Add any active capability permissions not already present
    for (const p of [...activePermissions].sort()) {
        if (!filteredPerms.includes(p)) filteredPerms.push(p);
    }
    filteredPerms.sort();

    if (JSON.stringify(currentPerms) !== JSON.stringify(filteredPerms)) {
        appJson.expo.android.permissions = filteredPerms;
        fs.writeFileSync(APP_JSON_PATH, JSON.stringify(appJson, null, 2) + '\n', 'utf-8');
        console.log('[sync] Updated app.json permissions');
    } else {
        console.log('[sync] app.json permissions up to date');
    }

    // --- Sync AndroidManifest.xml ---
    let manifest = fs.readFileSync(MANIFEST_PATH, 'utf-8');

    // 1. Replace CAPABILITY_PERMISSIONS block with sorted active permissions
    const permLines = [...activePermissions].sort()
        .map(p => `  <uses-permission android:name="${p}"/>`)
        .join('\n');
    const permBlockRe = /([ \t]*<!-- CAPABILITY_PERMISSIONS:start -->)[\s\S]*?([ \t]*<!-- CAPABILITY_PERMISSIONS:end -->)/;
    if (permBlockRe.test(manifest)) {
        manifest = manifest.replace(
            permBlockRe,
            `  <!-- CAPABILITY_PERMISSIONS:start -->\n${permLines}\n  <!-- CAPABILITY_PERMISSIONS:end -->`,
        );
    } else {
        console.warn('[sync] WARNING: CAPABILITY_PERMISSIONS block not found in AndroidManifest.xml');
    }

    // 2. Bidirectional sync of non-permission manifest blocks (anchor ↔ start/end block)
    for (const [id, blocks] of Object.entries(CAPABILITY_MANIFEST_BLOCKS)) {
        const isDisabled = disabledIds.has(id);
        for (const { anchor, xml } of blocks) {
            const blockContent = `  <!-- CAPABILITY:${id}:start -->\n${xml}\n  <!-- CAPABILITY:${id}:end -->`;
            const blockRe = new RegExp(
                `[ \\t]*<!-- CAPABILITY:${id}:start -->[\\s\\S]*?<!-- CAPABILITY:${id}:end -->`,
            );
            if (isDisabled) {
                // block → anchor
                manifest = manifest.replace(blockRe, anchor);
                // if already anchor, no-op
            } else {
                // anchor → block; se já é block (já ativo): no-op
                manifest = manifest.replace(anchor, blockContent);
            }
        }
    }

    const currentManifest = fs.readFileSync(MANIFEST_PATH, 'utf-8');
    if (manifest !== currentManifest) {
        fs.writeFileSync(MANIFEST_PATH, manifest, 'utf-8');
        console.log('[sync] Updated AndroidManifest.xml');
    } else {
        console.log('[sync] AndroidManifest.xml up to date');
    }
}

/**
 * Reads lib/capabilities/index.ts to determine the canonical order of capabilities.
 */
function getCapabilityOrder(): string[] {
    const indexSrc = fs.readFileSync(path.join(LIB_CAPS_DIR, 'index.ts'), 'utf-8');
    // Find ALL_CAPABILITIES array block
    const arrayMatch = indexSrc.match(/ALL_CAPABILITIES[^=]*=\s*\[([^\]]*)\]/s);
    if (!arrayMatch) return [];
    return [...arrayMatch[1].matchAll(/(\w+)Capability/g)].map(m => {
        // Convert camelCase capability name back to id (e.g. clipboardCapability → clipboard)
        return m[1];
    });
}

async function main(): Promise<void> {
    console.log('[sync] Reading capabilities from lib/capabilities/...');

    const indexSrc = fs.readFileSync(path.join(LIB_CAPS_DIR, 'index.ts'), 'utf-8');
    const disabledIds = parseDisabledCapabilities(indexSrc);
    if (disabledIds.size > 0) {
        console.log(`[sync] Disabled capabilities: ${[...disabledIds].join(', ')}`);
    }

    const order = getCapabilityOrder();

    // Parse all capability files
    const parsed = new Map<string, CapDoc>();
    for (const file of fs.readdirSync(LIB_CAPS_DIR)) {
        if (!file.endsWith('.ts') || file === 'index.ts' || file === 'types.ts') continue;
        const cap = parseCapabilityFile(path.join(LIB_CAPS_DIR, file));
        if (cap) parsed.set(cap.id, cap);
    }

    // Sort by canonical order from index.ts, then alphabetical for any extras
    const allCaps: CapDoc[] = [];
    for (const id of order) {
        if (parsed.has(id)) allCaps.push(parsed.get(id)!);
    }
    for (const [id, cap] of parsed) {
        if (!order.includes(id)) allCaps.push(cap);
    }

    // Active capabilities only (for Firebase docs)
    const caps = allCaps.filter(c => !disabledIds.has(c.id));

    console.log(`[sync] Found ${allCaps.length} capability module(s), ${caps.length} active: ${caps.map(c => c.id).join(', ')}`);

    for (const cap of caps) {
        const filePath = path.join(CAPS_DIR, `${cap.id}.ts`);
        fs.writeFileSync(filePath, generateCapabilityFile(cap), 'utf-8');
        console.log(`[sync] Wrote ${path.relative(process.cwd(), filePath)}`);
    }

    // Remove stale auto-generated files no longer in active capabilities
    const currentIds = new Set(caps.map(c => `${c.id}.ts`));
    for (const f of fs.readdirSync(CAPS_DIR)) {
        if (!f.endsWith('.ts') || f === 'types.ts' || f === 'index.ts') continue;
        if (!currentIds.has(f)) {
            const filePath = path.join(CAPS_DIR, f);
            const first = fs.readFileSync(filePath, 'utf-8').trimStart();
            if (first.startsWith('/**\n * AUTO-GENERATED')) {
                fs.unlinkSync(filePath);
                console.log(`[sync] Removed stale: ${f}`);
            }
        }
    }

    // Always regenerate the aggregate index
    const indexPath = path.join(CAPS_DIR, 'index.ts');
    fs.writeFileSync(indexPath, generateIndexFile(caps), 'utf-8');
    console.log(`[sync] Wrote ${path.relative(process.cwd(), indexPath)}`);

    // Sync Android permissions (app.json + AndroidManifest.xml)
    syncPermissions(allCaps.map(c => c.id), disabledIds);

    console.log('[sync] Done.');
}

main().catch(err => { console.error('[sync] Error:', err); process.exit(1); });
