/**
 * sync-capability-docs.ts
 *
 * Extracts { id, displayName, minVersion, docs } from every capability module
 * in lib/capabilities/ by statically parsing the TypeScript source files.
 * This avoids the need to execute native RN/Expo modules at build time.
 *
 * Run:  npm run sync-capabilities
 *
 * Generated files are committed to git — Firebase deploy is self-contained.
 */

import * as path from 'path';
import * as fs from 'fs';

const LIB_CAPS_DIR = path.resolve(__dirname, '../lib/capabilities');
const CAPS_DIR = path.resolve(__dirname, '../firebase/functions/src/capabilities');
const BANNER = `/**
 * AUTO-GENERATED by scripts/sync-capability-docs.ts
 * DO NOT EDIT MANUALLY — edit the source in lib/capabilities/<id>.ts instead.
 */`;

interface CapDoc {
    id: string;
    displayName: string;
    minVersion: string;
    docs: string;
}

/**
 * Extracts the value of a simple string field (single or double quotes, or backtick)
 * from a TypeScript source string.
 * Handles:  id: 'foo',  displayName: "Bar",  minVersion: `1.0.0`,
 */
function extractStringField(src: string, field: string): string {
    // Single/double quoted strings
    const reSingleDouble = new RegExp(`\\b${field}\\s*:\\s*(['"])(.*?)\\1`, 's');
    const m1 = reSingleDouble.exec(src);
    if (m1) return m1[2];
    // Backtick strings (no interpolation expected for these fields)
    const reBacktick = new RegExp(`\\b${field}\\s*:\\s*\`(.*?)\``, 's');
    const m2 = reBacktick.exec(src);
    if (m2) return m2[1];
    return '';
}

/**
 * Extracts the docs template literal content.
 * The docs field is always a tagged template literal: docs: `...`,
 * It may contain nested backticks escaped as \`.
 */
function extractDocsField(src: string): string {
    // Find the docs field start
    const docsIdx = src.search(/\bdocs\s*:\s*`/);
    if (docsIdx === -1) return '';

    // Find the opening backtick
    const backtickStart = src.indexOf('`', docsIdx + src.slice(docsIdx).search(/\bdocs\s*:\s*`/) - docsIdx);
    const openIdx = src.indexOf('`', docsIdx);
    if (openIdx === -1) return '';

    // Walk forward to find the closing backtick (accounting for \` escapes)
    let i = openIdx + 1;
    while (i < src.length) {
        if (src[i] === '\\') { i += 2; continue; }
        if (src[i] === '`') break;
        i++;
    }
    return src.slice(openIdx + 1, i)
        .replace(/\\`/g, '`')
        .replace(/\\\$/g, '$');
}

function parseCapabilityFile(filePath: string): CapDoc | null {
    const src = fs.readFileSync(filePath, 'utf-8');

    // Skip non-capability files (types, index, helpers)
    if (!src.includes('CapabilityModule')) return null;
    if (!src.includes('getInjectedJS')) return null;

    const id = extractStringField(src, 'id');
    const displayName = extractStringField(src, 'displayName');
    const minVersion = extractStringField(src, 'minVersion');
    const docs = extractDocsField(src);

    if (!id || !docs) {
        console.warn(`[sync] Warning: could not extract id/docs from ${path.basename(filePath)}`);
        return null;
    }

    return { id, displayName, minVersion, docs };
}

function escapeTemplateLiteral(s: string): string {
    return s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

function generateCapabilityFile(cap: CapDoc): string {
    return `${BANNER}

import { FirebaseCapabilityDoc } from './types';

const ${cap.id}Capability: FirebaseCapabilityDoc = {
    id: ${JSON.stringify(cap.id)},
    displayName: ${JSON.stringify(cap.displayName)},
    minVersion: ${JSON.stringify(cap.minVersion)},
    docs: \`${escapeTemplateLiteral(cap.docs)}\`,
};

export default ${cap.id}Capability;
`;
}

function generateIndexFile(caps: CapDoc[]): string {
    const imports = caps.map(c => `import ${c.id}Capability from './${c.id}';`).join('\n');
    const list = caps.map(c => `    ${c.id}Capability,`).join('\n');
    return `${BANNER}

import { SYSTEM_PREAMBLE } from '../prompts';
import { FirebaseCapabilityDoc } from './types';
${imports ? '\n' + imports : ''}

export const ALL_CAPABILITIES: FirebaseCapabilityDoc[] = [
${list}
];

/** Returns true if appVersion >= minVersion (simple semver comparison). */
export function versionGte(appVersion: string, minVersion: string): boolean {
    const parse = (v: string) => v.split('.').map(n => parseInt(n, 10) || 0);
    const [maj1, min1, pat1] = parse(appVersion);
    const [maj2, min2, pat2] = parse(minVersion);
    if (maj1 !== maj2) return maj1 > maj2;
    if (min1 !== min2) return min1 > min2;
    return pat1 >= pat2;
}

/**
 * Builds the system instructions for a given app version.
 * Only capabilities with minVersion <= appVersion are included.
 */
export function buildSystemInstructions(
    appVersion: string,
    caps: FirebaseCapabilityDoc[],
): string {
    if (caps.length === 0) {
        return SYSTEM_PREAMBLE;
    }
    const available = caps.filter(c => versionGte(appVersion, c.minVersion));
    return SYSTEM_PREAMBLE + '\\n\\n--- API DOCUMENTATION ---\\n\\n' + available.map(c => c.docs).join('\\n\\n');
}
`;
}

/**
 * Reads lib/capabilities/index.ts to determine the canonical order of capabilities.
 */
function getCapabilityOrder(): string[] {
    const indexSrc = fs.readFileSync(path.join(LIB_CAPS_DIR, 'index.ts'), 'utf-8');
    // Find ALL_CAPABILITIES array block
    const arrayMatch = indexSrc.match(/ALL_CAPABILITIES[^=]*=\s*\[([^\]]*)\]/s);
    if (!arrayMatch) return [];
    return [...arrayMatch[1].matchAll(/(\w+)Capability/g)].map(m => {
        // Convert camelCase capability name back to id (e.g. clipboardCapability → clipboard)
        return m[1];
    });
}

async function main(): Promise<void> {
    console.log('[sync] Reading capabilities from lib/capabilities/...');

    const order = getCapabilityOrder();

    // Parse all capability files
    const parsed = new Map<string, CapDoc>();
    for (const file of fs.readdirSync(LIB_CAPS_DIR)) {
        if (!file.endsWith('.ts') || file === 'index.ts' || file === 'types.ts') continue;
        const cap = parseCapabilityFile(path.join(LIB_CAPS_DIR, file));
        if (cap) parsed.set(cap.id, cap);
    }

    // Sort by canonical order from index.ts, then alphabetical for any extras
    const caps: CapDoc[] = [];
    for (const id of order) {
        if (parsed.has(id)) caps.push(parsed.get(id)!);
    }
    for (const [id, cap] of parsed) {
        if (!order.includes(id)) caps.push(cap);
    }

    console.log(`[sync] Found ${caps.length} capability module(s): ${caps.map(c => c.id).join(', ')}`);

    for (const cap of caps) {
        const filePath = path.join(CAPS_DIR, `${cap.id}.ts`);
        fs.writeFileSync(filePath, generateCapabilityFile(cap), 'utf-8');
        console.log(`[sync] Wrote ${path.relative(process.cwd(), filePath)}`);
    }

    // Remove stale auto-generated files no longer in ALL_CAPABILITIES
    const currentIds = new Set(caps.map(c => `${c.id}.ts`));
    for (const f of fs.readdirSync(CAPS_DIR)) {
        if (!f.endsWith('.ts') || f === 'types.ts' || f === 'index.ts') continue;
        if (!currentIds.has(f)) {
            const filePath = path.join(CAPS_DIR, f);
            const first = fs.readFileSync(filePath, 'utf-8').trimStart();
            if (first.startsWith('/**\n * AUTO-GENERATED')) {
                fs.unlinkSync(filePath);
                console.log(`[sync] Removed stale: ${f}`);
            }
        }
    }

    // Always regenerate the aggregate index
    const indexPath = path.join(CAPS_DIR, 'index.ts');
    fs.writeFileSync(indexPath, generateIndexFile(caps), 'utf-8');
    console.log(`[sync] Wrote ${path.relative(process.cwd(), indexPath)}`);

    console.log('[sync] Done.');
}

main().catch(err => { console.error('[sync] Error:', err); process.exit(1); });
